### ISSUE TITLE
Remove java and go dependencies in WORKSPACE file

### ISSUE THREAD

**Issue by software-dov** [googleapis/gapic-generator-cpp#35]
In order to build the operations proto library (provided by the `com_google_googleapis` repository) and generate a corresponding C++ library (currently provided by gax) the WORKSPACE file needs to load and set up the java and go repositories from `com_google_googleapis`. This is a hack and adds unnecessary dependencies.

Tracking bug to remove the hack.

**Comment by vam-google** [comment]
This repository is obsolete. Closing.
